version: "3.9"
services:
  web:
    build: .
    container_name: myapp_web
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
    working_dir: /myapp
    command: bash -c "bundle install && bin/rails s -b 0.0.0.0"
    tty: true
    stdin_open: true
