default_sqlite: &default_sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default_sqlite
  database: db/development.sqlite3

test:
  <<: *default_sqlite
  database: db/test.sqlite3

# PostgreSQL 用 default（production 向け）
default_pg: &default_pg
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: namerou
  password: <%= ENV['PRODUCTION_DB_PASSWORD'] %>

production:
  <<: *default_pg
  database: malatangenerator_production