name: Rails CI

on:
  push:
    branches: [ "suuryousentaku" ]
  pull_request:
    branches: [ "suuryousentaku" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@localhost:5432/test_db

    steps:
    - uses: actions/checkout@v3

    - name: Install Japanese fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-ipafont-gothic

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.2 # ← あなたの使っているバージョンに合わせてください
        bundler-cache: true

    - name: Set up database
      run: |
        cp config/database.yml.github-actions config/database.yml
        bundle exec rails db:prepare

    - name: Run tests
      run: bundle exec rspec

    - name: Set up Chrome for Capybara
      uses: browser-actions/setup-chrome@v1

    - name: Prepare DB
      run: |
        bundle exec rails db:schema:load RAILS_ENV=test
        bundle exec rails db:seed RAILS_ENV=test

    - name: Run system specs
      run: bundle exec rspec spec/system

    - name: Upload Capybara screenshots
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: capybara-screenshots
        path: tmp/capybara
